[package]
name = "wandering_inn_scraper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mail-builder = "0.3.0"
mail-send = "0.4.0"
serde = "1.0.180"
serde_json = "1.0.104"
tokio = { version = "1.29.1", features = ["full"] }
